/**
 * Full "deep throat" report: direct deps + transitive tree + something-old chains.
 */

import { reportToMarkdown } from './report.js';

/**
 * @param {object} directReport - from analyze()
 * @param {object} options
 * @param {string} [options.projectName] - e.g. "citrascope"
 * @param {string} [options.projectUrl] - e.g. "https://github.com/citra-space/citrascope"
 * @param {string} [options.projectDescription] - one-line from pyproject
 * @param {Array<{ name: string, version: string, chain: string, why: string }>} [options.somethingOldChains] - from buildSomethingOldChains
 * @param {string} [options.pipTreeText] - raw pipdeptree text output for <details> block
 * @param {string} [options.ecosystem] - npm | pip | go
 * @param {boolean} [options.hadPipTree] - true if transitive tree was included
 * @returns {string} full markdown report
 */
export function buildFullReport(directReport, options = {}) {
  const {
    projectName = 'project',
    projectUrl = '',
    projectDescription = '',
    somethingOldChains = [],
    pipTreeText = '',
    ecosystem = directReport.ecosystem || 'npm',
    hadPipTree = false,
  } = options;

  const title = projectName ? `${projectName} — Full Dependency Report` : 'Full Dependency Report';
  const lines = [
    `# ${title}`,
    '',
    `**Generated:** ${new Date().toISOString().slice(0, 10)}`,
    `**Tools:** [UpshiftAI](https://upshiftai.dev) (direct deps)${pipTreeText ? ' + **pipdeptree** (full transitive tree)' : ''}`,
    '',
  ];
  if (projectUrl) {
    lines.push(`**Project:** ${projectUrl}`);
    if (projectDescription) lines.push(`**About:** ${projectDescription}`);
    lines.push('', '');
  } else if (projectDescription) {
    lines.push(`**About:** ${projectDescription}`, '', '');
  }

  if (somethingOldChains.length > 0) {
    lines.push('---', '', '## The "something old" chains (transitive)', '');
    lines.push('When your guy says "everything depends on something else made by someone awhile ago that runs on old Python," this is where it shows up in the **actual installed tree**:', '', '');
    lines.push('| Transitive dep | Pulled in by | Why it matters |');
    lines.push('|----------------|--------------|----------------|');
    for (const row of somethingOldChains) {
      lines.push(`| **${row.name}** | ${row.chain} | ${row.why} |`);
    }
    lines.push('', '---', '', '');
  }

  if (pipTreeText) {
    lines.push('## Full transitive tree (from pipdeptree)', '');
    lines.push('Below is the full tree from `pip install -e ".[dev]"` (or your install) then `pipdeptree`. So this is the **real** dependency graph (with versions pip chose).', '', '');
    lines.push('<details>');
    lines.push('<summary>Click to expand: full pipdeptree output</summary>');
    lines.push('');
    lines.push('```');
    lines.push(pipTreeText.trim());
    lines.push('```');
    lines.push('');
    lines.push('</details>');
    lines.push('', '---', '', '');
  }

  lines.push('## Direct dependencies (UpshiftAI)', '');
  lines.push(reportToMarkdown(directReport));
  lines.push('');
  lines.push('---');
  lines.push('');
  if (ecosystem === 'pip' && !hadPipTree) {
    lines.push('*Full report generated by upshiftai-deps report. To include transitive "something old" chains and the full tree, re-run with `--full-tree` (or `--pip-tree tree.json` after `pipdeptree -o json > tree.json`).*');
  } else if (hadPipTree) {
    lines.push('*Full report generated by upshiftai-deps report. Transitive data was included from pipdeptree.*');
  } else {
    lines.push('*Full report generated by upshiftai-deps report.*');
  }

  return lines.join('\n');
}
